[project]
name = "autoipaalign-core"
version = "0.1.0"
description = "Core library and CLI for automatic IPA transcription and forced alignment"
requires-python = ">=3.9"
dependencies = [
    "transformers[torch]",
    "librosa",
    "tgt",
    "soundfile",
    "tyro",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
    "ruff",
]

[project.scripts]
autoipaalign = "autoipaalign_core.cli:main"


[build-system]
requires = ["uv_build>=0.8.22,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest-datadir>=1.8.0",
]
